### ISSUE TITLE
Ανάθεση Έργων

### ISSUE THREAD

**Issue by HomiG** [DimitrisKostorrizos/ProjectSoftwareEngineering#1]
**Για 28/03:** 
Αλέξανδρος: Σχεδίαση ενδεικτικών UI
Δημήτρης: Project Description, μελέτη των "charts"
Όμηρος: Υπομέρους Tasks 
Δήμητρα: Risk Assessment

**Comment by AlexanDelimi** [comment]
Για 28?/04/20
Ο χ ελεγχει τον Υ
Χ                             Υ
Αλεξανδρος-> Ομηρος
Δημητρα-> Αλέξανδρος
Δημητρης_>Δημητρα
Ομηρος-> Δημητρης

και αφου δουμε τις διορθωσεις ξεκιναμε τα robustness μας

**Comment by AlexanDelimi** [comment]
Για  1/05
Για επομενη φορα:
Ο χ ελεγχει τον Υ
Χ                             Υ
Αλεξανδρος-> Ομηρος
Δημητρα-> Αλέξανδρος
Δημητρης_>Δημητρα
Ομηρος-> Δημητρης
Μετα αλλαζουμε use cases βρισκουμε τα atrributes που προκυπτουν για το domain

**Comment by HomiG** [comment]
Έχουμε να:
- Σβήσουμε τα Log In απο τα προηγουμενα παραδοτέα 
- Να ολοκληρώσουμε τα Mock-up Screens
- Sequence Diagrams
